# Generated by Django 3.2.6 on 2021-08-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='thubnail',
            field=models.FileField(default='photo/default-music.png', upload_to='photo'),
        ),
    ]
