# Generated by Django 3.2.6 on 2021-08-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songs_thubnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='thubnail',
            field=models.ImageField(default='photo/default-music.png', upload_to='photo'),
        ),
    ]
